name: Run Pytest
on:
  workflow_call:
    inputs:
      image_tag:
        description: 'Tag of the image to test'
        type: string
        default: 'latest'
      image_registry:
        description: 'Artifact Registry repo (images or images-dev)'
        type: string
        default: 'images-dev'
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag of the image to test'
        type: string
        default: 'latest'
      image_registry:
        description: 'Artifact Registry repo (images or images-dev)'
        type: string
        default: 'images-dev'

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    environment: 'development'

    steps:
    - uses: actions/checkout@v4

    - id: 'google-cloud-auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

    - id: 'google-cloud-sdk-setup'
      name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v2

    - name: 'gcloud docker auth'
      run: |
        gcloud auth configure-docker australia-southeast1-docker.pkg.dev

    - name: Run unit tests in container
      run: |
        # Use provided tag if available, otherwise fallback to ref_name-latest
        IMAGE_TAG="${{ inputs.image_tag }}"
        if [[ "$IMAGE_TAG" == "latest" ]]; then
          IMAGE_TAG="${{ github.ref_name }}"
          IMAGE_TAG="${IMAGE_TAG//\//-}-latest"
        fi

        docker run --rm \
          --shm-size=2gb \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          australia-southeast1-docker.pkg.dev/cpg-common/${{ inputs.image_registry }}/popgen_rbceq2:$IMAGE_TAG \
          bash -c "pip install pytest pytest-mock toml && pytest -vs tests"
